fstests: generic/042: increase size for btrfs and ext4
While testing for shutdown, I found that generic/042 sets a size of
25M, which is too small for btrfs and ext4 filesystems on a 64k pagesize,
set it to 300M.

wrote 26214400/26214400 bytes at offset 0
25 MiB, 6400 ops; 0.0468 sec (533.618 MiB/sec and 136606.1900 ops/sec)
ERROR: '/mnt/scratch/042.img' is too small to make a usable filesystem
ERROR: minimum size for each btrfs device is 114294784

Signed-off-by: Anand Jain <anand.jain@oracle.com>